### ISSUE TITLE
Error running - lua require'colorizer'.setup()

### ISSUE THREAD

**Issue by kshay-pop** [norcalli/nvim-colorizer.lua#12]
After running `lua require'colorizer'.setup()` I get this reponse `&termguicolors must be set`

I am using - 
`fish, version 3.0.2`
`nvim v0.4.2`
`macOS Catalina build (19A602)`

**Comment by norcalli** [comment]
You should add `set termguicolors` before that line in your `init.vim` assuming your terminal supports true color.

See this if it still fails: https://gist.github.com/XVilka/8346728
