### ISSUE TITLE
keep everything under colorizer namespace？

### ISSUE THREAD

**Issue by wsdjeg** [norcalli/nvim-colorizer.lua#20]
hello, thanks for create such plugin. but can you keep everything under colorizer namespace. when using this plugin. I can not load my own nvim module.

**Comment by justinmk** [comment]
Ah, this happens because `lua/nvim.lua` is on the runtimepath / luapath. I think putting everything in `lua/colorizer/...` will fix it, though it means that the imports change to `require('colorizer.nvim')`, etc.

**Comment by norcalli** [comment]
Yeah I'm fixing it right now. I'm moving the files to `colorizer/deps/` which doesn't conflict with the `colorizer.lua` plugin and is unlikely to conflict with anything else.

**Comment by norcalli** [comment]
@wsdjeg try updating and let me know if you run into any more problems.

@justinmk I should do this for all of my plugins and then make a "writing lua plugins for neovim" tutorial/best practices :P

**Comment by wsdjeg** [comment]
ok thanks

**Comment by justinmk** [comment]
> a "writing lua plugins for neovim" tutorial/best practices :P

could be a patch to `if_lua.txt` :) There is some treatment in `:help lua-require` and/or `:help lua-intro` but it could be expanded.
