### ISSUE TITLE
Highlight only full word matches

### ISSUE THREAD

**Issue by meain** [norcalli/nvim-colorizer.lua#24]
![](https://i.imgur.com/iZcTVJx.png)

Might wanna check if they are full words or surround by only things like `'`, `"` or `;` or space ... or even check if not surrounded by alphaneumeric

**Comment by norcalli** [comment]
Try updating. This was addressed before.

**Comment by norcalli** [comment]
Can you put your revision that you are using? `git log | head -n1` would be sufficient in the directory it's installed. If you are using vim-plug, for example, it would be in `~/.config/nvim/plugged/nvim-colorizer.lua`.

**Comment by norcalli** [comment]
@meain Actually, here's an even easier command:

Please paste the output of:
```sh
find ~/.config/nvim/ -type d -name 'nvim-colorizer.lua' -exec git rev-parse HEAD \;
```

**Comment by meain** [comment]
I'm sorry. I had an old version.
