### ISSUE TITLE
Bug: Index out of bounds

### ISSUE THREAD

**Issue by adelarsq** [norcalli/nvim-colorizer.lua#25]
Sometimes shows this message when open a file:

```
Error executing lua callback: ~/.vim/plugged/nvim-colorizer.lua//lua/colorizer.lua:518: Index out of bounds
```

I'm using the last version from `master`.

**Comment by norcalli** [comment]
Please don't ignore the bug template. I made it for a reason. While I will take this issue under consideration, this bug report isn't helpful at all, so I'm going to close this and give you another chance to make one.
