### ISSUE TITLE
Vim command to toggle highlighting

### ISSUE THREAD

**Issue by jcrd** [norcalli/nvim-colorizer.lua#27]
I want to toggle highlighting on-demand, like `:HexokinaseToggle`. Is this possible?

**Comment by norcalli** [comment]
There's no command for that right now, but I could add one. In the meantime, the functionality is already available via Lua, so you can do:

```lua
local colorizer = require'colorizer'
if colorizer.is_buffer_attached() then
  colorizer.detach_from_buffer()
else
  colorizer.attach_to_buffer()
end
```

or as a one line command:

```vim
command! ColorizerToggle lua local colorizer = require'colorizer' if colorizer.is_buffer_attached() then colorizer.detach_from_buffer() else colorizer.attach_to_buffer() end
```

**Comment by jcrd** [comment]
Hi, I can't find any reference to `is_buffer_attached` in the code or API docs.
Nonetheless, this is the functionality I was seeking and would appreciate the addition of a `ColorizerToggle` command.

**Comment by norcalli** [comment]
Wow you're right. That's my bad. Thanks for pointing that out!
