### ISSUE TITLE
Doesn't work when opening file as parameter

### ISSUE THREAD

**Issue by SevereOverfl0w** [norcalli/nvim-colorizer.lua#3]
e.g. `nvim foo.css` doesn't have highlights, but `nvim`, then `:e foo.css` does

**Comment by norcalli** [comment]
Hmm, I'm not able to reproduce that right now, even with a minimal vimrc:

```vim
set runtimepath+=~/.config/nvim/plugged/nvim-colorizer.lua/
set termguicolors
lua require'colorizer'.setup()
```

If you try the above (but replacing the path with where colorizer is installed on your computer) and write it to something like `/tmp/minimal.vim`, does it still not work with `nvim -u /tmp/minimal.vim foo.css`?

**Comment by SevereOverfl0w** [comment]
Closing, as I know my setup is pretty weird anyway :)

**Comment by norcalli** [comment]
Sounds good! I'll see about making it clearer how to use it in atypical setups. The main useful api is `colorizer.attach_to_buffer(buf)`, where `colorizer.nvim_buf_attach(0)` attaches to the current buffer and continuously updates it, but I see you saw inside and found `COLORIZER_SETUP_HOOK()` which works even better, haha.
