### ISSUE TITLE
Bug: "attempt to call field 'create_namespace' (a nil value)"

### ISSUE THREAD

**Issue by TannerYoung** [norcalli/nvim-colorizer.lua#37]
**Describe the bug**
When enabling the plugin it causes neovim to crash

**To Reproduce**
init.vim:
```
:let mapleader = ";"

:set number hlsearch tabstop=2 shiftwidth=2 expandtab
:set termguicolors
:syntax on
:set bg=dark

:map ' $
:noremap! jk <esc>
:noremap! <esc> <nop>
:nnoremap <leader>ev :vsplit $MYVIMRC<cr>
:nnoremap <leader>sv :source $MYVIMRC<cr>

call plug#begin()
Plug 'morhetz/gruvbox'

Plug 'norcalli/nvim-colorizer.lua'

call plug#end()
lua require 'colorizer'.setup()
:colorscheme gruvbox

```

terminal: termite

**Expected behavior**
For it to work and not crash

**Operating System:**
Ubuntu 18.04

**Neovim Version:**
0.2.2

**Colorizer Version:**
479bec1d73abd2b4f596b1d2c03c4f1f8e36ab76

**Additional context**
Output on startup:

```
Error detected while processing /home/<user>/.config/nvim/init.vim:
line   20:
E5105: Error while calling lua chunk: ...config/nvim/plugged/nvim-colorizer.lua/lua/colorizer.lua:326: attempt to call field 'create_namespace' (a nil value)
Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
from the readme:

> Requires Neovim >= 0.4.0

**Comment by TannerYoung** [comment]
Welp that makes sense and seems obvious in retrospect. Guess I suspected
the Ubuntu 18.04 package to be somewhat up to date for neovim.
