### ISSUE TITLE
Errors when passing options

### ISSUE THREAD

**Issue by ahmedelgabri** [norcalli/nvim-colorizer.lua#4]
So I'm trying to do this `plugin/colorizer.vim`

```vim
lua require 'colorizer'.setup ({
  '*';
}, {
  mode = 'foreground';
  rgb_fn = true;
})
```

But when I open neovim, I get this error

```txt
|| Error detected while processing
/Users/ahmed/.dotfiles/files/.vim/plugin/colorizer.vim|5| 
|| E5104: Error while creating lua chunk: [string "<VimL compiled string>"]:1: unexpected symbol near '<eof>'
|| line    6:
|| E20: Mark not set
|| line    7:
|| E20: Mark not set
|| line    8:
|| E492: Not an editor command:   html = { mode = 'background' };
|| line    9:
|| E492: Not an editor command: }, { mode = 'foreground' })
```

But this works fine

```vim
lua require 'colorizer'.setup ()
```

**Comment by norcalli** [comment]
The `lua` command only operates on a single line, so your code is being partially interpreted as `viml` code. The correct way to do it from viml would be:

```viml
lua <<EOF
require 'colorizer'.setup ({
  '*';
}, {
  mode = 'foreground';
  rgb_fn = true;
})
EOF
```

As a recommendation, I prefer to keep an `init.lua` file under `~/.config/nvim/lua/` where I put my Lua code, and then just require it once as `lua require'init'` from init.vim.

**Comment by ahmedelgabri** [comment]
It works 👍 

> As a recommendation, I prefer to keep an `init.lua` file under `~/.config/nvim/lua/` where I put my Lua code, and then just require it once as `lua require'init'` from init.vim.

That's a nice idea, thanks.

---

Two small requests: 

- exclude filetypes (_it's currently highlighting `minpack#add`) for example in `.vim` files_
- parsing `rgba` too

But overall, thanks again for the plugin!

**Comment by norcalli** [comment]
I agree with the exclusion idea, I think I can work that in, and rgba is definitely planned, I just got very tired and wanted to sleep by the time I had finished, haha.

As far as `#add` goes, I also noticed the same thing with `#def`ine. I'm going to add an option to allow disabling `#RGB` codes as soon as I can figure out what to name it.

**Comment by ahmedelgabri** [comment]
No problem at all! I understand, was just throwing some ideas.

> As far as `#add` goes, I also noticed the same thing with `#def`ine. I'm going to add an option to allow disabling `#RGB` codes as soon as I can figure out what to name it.

If you disable this, then it will affect HEX support with shorthand in CSS, for example, is `#rrggbb` can be written as `#rgb`. that's why I asked for disabling per filetype so you have finer control over when you want to disable this.

```css
.foo { color: #bad; }

/* is the same as */

.foo { color: #bbaadd; }
```

In fact, some formatters/minifiers will convert the 2nd to be the first. So I wouldn't disable this to be honest.

**Comment by norcalli** [comment]
@ahmedelgabri I implemented rgba and exclusion, btw.

**Comment by ahmedelgabri** [comment]
Perfect, thank you!
