### ISSUE TITLE
How to load disabled?

### ISSUE THREAD

**Issue by adrian5** [norcalli/nvim-colorizer.lua#62]
I'd like to only enable the plugin on demand, but I don't know how to disable it by default. I use a regular `init.vim`.

**Comment by arsham** [comment]
Try only installing without calling `setup`. If you are using Packer:

```lua
use { 'norcalli/nvim-colorizer.lua' }
```

Then you can execute `:ColorizerToggle` to toggle it whenever you want.

Is that what you're after?

**Comment by adrian5** [comment]
Yes, that's what I wanted – thank you! I wasn't aware the call to `.setup()` was optional, and that the commands would be available without it.
