### ISSUE TITLE
Doesn't work for *.conf filetypes (and maybe others?)

### ISSUE THREAD

**Issue by filipekiss** [norcalli/nvim-colorizer.lua#9]
I installed your plugin and was working with a `*.conf` file and noticed the colors weren't working. I thought I was messing the configuration, but it works when I'm on a `*.sass` file. [Here's a gist](https://gist.github.com/filipekiss/7dcab93717250e09ed91fa846036a8a2) with both files and a `minimal.vim`rc for reproduction.

Great plugin, btw!

| Sass File | Conf File |
| -- | -- |
|![image](https://user-images.githubusercontent.com/48519/67097155-d2d61500-f1b9-11e9-862e-48df4c879acb.png)| ![image](https://user-images.githubusercontent.com/48519/67097197-e5e8e500-f1b9-11e9-96d3-9d60a8d476e9.png)|

**Comment by norcalli** [comment]
I can confirm this problem! I have no idea why, yet, though, but I'm working on another few issues, so I'll try to address it very soon. And thanks.

**Comment by filipekiss** [comment]
@norcalli I think I found out the problem: The `.conf` file has no filetype in vim. If you `set ft=conf` the colors come up as if magic!

**Comment by norcalli** [comment]
The problem probably originates in the `FileType` autocmd [EDIT: as you just mentioned, haha].

The setup function is just a thin wrapper around calling `colorizer.attach_to_buffer()`.

If you do `:lua require'colorizer'.attach_to_buffer(0)`, it will highlight the current buffer.

You can use this with options too (as the second parameter). In the meantime, it would seem that making an autocmd for `BufReadPost *.conf setl ft=conf` would work.

**Comment by filipekiss** [comment]
Yeah, adding the filetype solves the problem for me. Great plugin ♥️ Thank you so much!

**Comment by norcalli** [comment]
@filipekiss yeah, adding it to the README is a good idea. I'll keep this issue open for now for future travelers.

**Comment by filipekiss** [comment]
Made a pull-request with the information. :D Hope it helps.
