### ISSUE TITLE
:ColorizerAttachToBuffer by default

### ISSUE THREAD

**Issue by MannyFay** [norcalli/nvim-colorizer.lua#97]
How can I enable the colorizer by default if I open Neovim and attach it automatically to every buffer I open?

I've tried different auto commands in my `nvim-colorizer.lua` but without any results. The Colorizer is working if I attach it manually in command line.

**Comment by gongfarmer** [comment]
It sounds like the setup() function is not running at all, or maybe not early enough.

I started hitting this same bug after switching my neovim config from Packer to Lazy.

For me it was solved by changing this line in lua/plugins/init.lua:

`'norcalli/nvim-colorizer.lua'`

to this:

```lua
{
    'norcalli/nvim-colorizer.lua',
    config = function()
      require("colorizer").setup()
    end,
  },
```

I thought that Lazy would run setup() automatically, but apparently it did not.

**Comment by piersolenski** [comment]
Would be great if it could support `config = true` with Lazy!

**Comment by MannyFay** [comment]
Thanks @gongfarmer!
This works for me with Packer.

**Comment by MannyFay** [comment]
Thanks @gongfarmer!
This works for me with Packer.

**Comment by hellmind** [comment]
I still need a way to activate it at startup using Lazy

**Comment by Felipe-9** [comment]
Just add the event "BufRead"
